### ISSUE TITLE
Bug: Dots in keys lead to wrong results

### ISSUE THREAD

**Issue by daniel-rikowski** [fnando/glob#17]
## Description

I'm using this gem as part of your other project `i18n-js`.

In my translation YAML files I sometimes use dots in keys, like this:

```yaml
de:
  media_types:
    image:
      jpeg: JPEG
    application:
      msword: Word 97-2003
      'vnd.openxmlformats-officedocument.wordprocessingml.document': Word 2007-365
      'vnd.oasis.opendocument.text': LibreOffice/OpenOffice
```

Unfortunately these translations cannot be extracted, because Glob flattens the hash into path-value maps. There it no longer can distinguish path segment delimiters from embedded dots in keys when extracting the values.

I know, it's debatable if translation keys like this should exist, but at least the Rails I18n API is fine with it and for a general purpose library it would be nice if Glob could handle all kinds of strings.

## How to reproduce

```ruby
h = { application: { 'vnd.oasis.opendocument.text' => 'LibreOffice/OpenOffice' } }
Glob.filter(h, ['application.*'])
```

## What do you expect

```ruby
{:application=>{:"vnd.oasis.opendocument.text"=>"LibreOffice/OpenOffice"}}
```

## What happened instead

```ruby
 {:application=>{:vnd=>{:oasis=>{:opendocument=>{:text=>nil}}}}}
```

## Software:

- Gem version: 0.3.0
- Ruby version: 3.1.2 (Windows)

## Full backtrace

N/A

## Solution/Proposal

The fix is relatively simple, just escape and later unescape the dots in keys:

```ruby
    # map.rb
    private def compute(value, path)
      if value.is_a?(Hash)
        value.map do |key, other_value|
          key = key.to_s.gsub('.', '\.') # <======= ADDED
          compute(other_value, "#{path}.#{key}")
        end
      else
        path.to_s
      end
    end
```

```ruby
    # query.rb
    def to_h
      symbolized_target = SymbolizeKeys.call(@target)

      paths.each_with_object({}) do |path, buffer|
        # segments = path.split(".").map(&:to_sym) # <====== REPLACED WITH:
        segments = path.split(/(?<!\\)\./).map { |s| s.gsub('\.', '.') }.map(&:to_sym)
        value = symbolized_target.dig(*segments)
        set_path_value(segments, buffer, value)
      end
    end
```

If you want I can create a PR for this...

Alternatively if you are concerned about performance it would also be possible to replace the dot (in its role as path segment delimiter) with a less-common marker character, for example "Information Separator One" (https://unicodeplus.com/U+001F)

**Comment by fnando** [comment]
Hey @daniel-rikowski! I created a pull request that attempts to fix this, but used `\\.` as the escape sequence, so `glob.paths` can work properly when trying to reuse its results. Can you please test it and let me know if it's good to go?

**Comment by daniel-rikowski** [comment]
Yes, this works great! Thank you very much!


PS: Since `unescape` is called a lot (> 20.000 in my i18n-js export), it might be beneficial to use a plain string search pattern instead of a regexp. gsub with a regexp is quite slow (that is if there are actual replacements)


https://github.com/fnando/glob/blob/33f58535dfdeb705f9942e4ebac7b0964586e873/lib/glob/query.rb#L44-L46



```ruby
require 'benchmark'
n = 500000
str = "a\\.string\\.with\\.dots"
Benchmark.bm do |x|
  x.report { n.times { str.gsub("\\.", '.') } }
  x.report { n.times { str.gsub(/\\\./, '.') } }
end
```

```
       user     system      total        real
   0.484000   0.000000   0.484000 (  0.479136)
   1.438000   0.000000   1.438000 (  1.440019)
```

For a string without any escaped dots the performance is almost identical though...
